config/routes.rb
Recipes::Application.routes.draw do

  resources :recipes

  root to: "recipes#index"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  belongs_to :recipe

  validates :name, :recipe_id, presence: true
  validates :amount, presence: true, numericality: {greater_than: 0}
  
  def self.parse(ingredient_list)
    ingredient_lines = ingredient_list.lines.delete_if &:empty?
    ingredients = []
    ingredient_lines.each do |i|
      if match = i.match(/([\d\.\/\s]+) \s (\w+) \s (.+)/x)
        ingredients << Ingredient.new(amount: Ingredient.parse_fraction(match[1]), unit: match[2], name: match[3])
      end
    end
    ingredients
  end
  
  def to_s
    "#{amount_fraction} #{unit} #{name}"
  end
  
  def amount_fraction
    rational_amount = amount.to_r
    floor = rational_amount.floor
    fraction = rational_amount - floor
    fraction_str = "<sup>#{fraction.numerator}</sup>&frasl;<sub>#{fraction.denominator}</sub>"
    # if both floor and fraction > 0, display both
    # floor only or fraction only > 0, display that
    # both 0, display 0
    # < 0, display "invalid"
    if floor > 0 || fraction > 0
      "#{floor if floor > 0} #{fraction_str if fraction > 0}"
    elsif floor == 0 && fraction == 0
      "0"
    else
      "<invalid>"
    end
  end

  def self.parse_fraction(str)
    match = str.match(/(\d*)\s*(\d+\/\d+)/)
    if match
      whole, fraction = match[1..2]
      value = whole.to_r + fraction.to_r
    else
      str.to_f
    end
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, :contents, presence: true
  validates :serving, numericality: {greater_than: 0}, presence: true
  
  attr_accessor :ingredient_list

  attr_accessible :photo
  has_attached_file :photo, styles: {medium: "300x300>", thumb: "100x100?"}, default_url: "/images/:style/cupcake.png"
    
  has_many :ingredients, dependent: :destroy
  validates_associated :ingredients, unless: "serving > 0"
   
  default_scope order: 'created_at DESC'
  
  def self.search(keyword)
    if keyword.blank?
      scoped
    else
      where ["name LIKE ?", "%#{keyword}%"]
    end
  end
  
  def parse(unparsed_contents)
    components = recipe_components(unparsed_contents)
    self.name, self.contents = components[:name], components[:contents]
    self.ingredients = Ingredient.parse(components[:ingredient_list])
    self
  end
  
  def recipe_components(unparsed_contents)
    unless @components 
      components = unparsed_contents.strip.gsub(/\r/, "").split("\n\n", 4)
      components = components - [components[1]] # ignore paragraph 2; it's just the Ingredients header
      @components = Hash[[:name, :ingredient_list, :contents].zip(components)]
    end
    @components
  end
  
  def scale(new_serving)
    new_serving ||= serving
    copy = self.dup
    copy.serving = new_serving
    ratio = new_serving.to_f / serving
    ingredients.each do |i|
      temp_i = i.dup
      temp_i.amount = ratio * i.amount
      copy.ingredients << temp_i
    end
    copy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.search(params[:search]).paginate page: params[:page], per_page: 30 
  end
  
  def show
    @recipe = Recipe.find(params[:id]).scale(params[:serving])
    unless @recipe.valid?
      flash[:error] = @recipe.errors.full_messages.join("<br />").html_safe # TODO move HTML logic into helper
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    if params[:unparsed_contents]
      @recipe = Recipe.new.parse(params[:unparsed_contents])
    else
      @recipe = Recipe.new(params[:recipe])
    end
    if @recipe.save
      flash[:success] = "Recipe saved"
      redirect_to recipes_path
    else
      flash.now[:error] = @recipe.errors.full_messages.join("\n")
      render action: 'index'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to(recipes_path, notice: 'Recipe was successfully updated.') 
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def prettify(contents)
    parsed = contents.match(/(.+?)\r\n(.+)/m)
    name = parsed[1] if parsed
    instructions = parsed[2] if parsed
    "<div class='recipe_name'>
      #{name.try(:titleize) || ''}
    </div>
    #{instructions.try(:gsub, /\r\n/, '<br />') || ''}"
  end
end

app/views/layouts/application.html.erb
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption' rel='stylesheet' type='text/css'>
<head>
  <title>Recipe app</title>
  <%= javascript_include_tag :all, cache: true %>
  <%= stylesheet_link_tag :all, media: :all %>
</head>
<body>
  <div class="container">
    <div class="flash">
      <% flash.each do |k, v| %>
        <div class=<%= k %>>
          <%= v %>
          <%= link_to "&times;".html_safe, "#", onclick: "$(this).parent().slideUp()" %>
        </div>
      <% end %>
    </div>
    <div>
      <%= form_tag recipes_path, {method: :get, class: "form-search"} do %>
        <%= search_field_tag :search, nil, class: "search-query" %> 
        <%= submit_tag "Find" %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>

app/views/recipes/_recipe.html.erb
<div class="recipe">
  <div class="recipe_contents">
    <p><%= recipe.id %>. </p>
    <div class='recipe_name'>
      <%= recipe.name.titleize %>
    </div>
    <% if (ingredients = recipe.ingredients).present? %>
      <%= form_tag(recipe_path(recipe.try(:id) || params[:id]), method: :get) do %> <%# a scaled recipe doesn't exist in the DB, so has to use params[:id] %>
        Servings: 
        <%= text_field_tag :serving, params[:serving] || recipe.serving %>        
        <%= submit_tag "Scale" %>
      <% end %>
      <strong>Ingredients</strong>
      <% ingredients.each do |i| %>
        <p><%= raw(i) %></p>
      <% end %>
    <% end %>
    <p><strong>Directions</strong></p>
    <%= raw(recipe.contents.try(:gsub, /\r\n/, '<br />')) %>
    <% if recipe.id %>
      <p>
        <%= link_to 'Edit', edit_recipe_path(recipe) %> | 
        <%= link_to raw("&times;"), recipe, confirm: 'Are you sure?', method: :delete %>
      </p>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>
<%= form_for(@recipe) do |f| %>
  <p>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.text_area :contents %>
  </p>
  <p>
    <%= f.submit 'Save' %>
  </p>
<% end %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<style>
  #new_recipe_forms {
    display: none;
  }
</style>
<div id="new_recipe_container">
  <div id="new_recipe_forms">
    <%= form_tag(Recipe.new) do |f| %>
      <strong>If the recipe has an Ingredients section, just dump it here:</strong>
      <p>
        <%= text_area_tag :unparsed_contents %>
      </p>
      <p>
        <%= submit_tag 'Parse this for me' %>
      </p>
    <% end %>
    <%= form_for(Recipe.new) do |f| %>
      <strong>If not, use this form:</strong>
      <p>
        <%= f.label :name %>
      </p>
      <p>
        <%= f.text_field :name, required: true %>
      </p>
      <p>
        <%= f.label :serving %>
      </p>
      <p>
        <%= f.text_field :serving %>
      </p>
      <p>
        <%= f.label :ingredient_list %>
      </p>
      <p>
        <%= f.text_area :ingredient_list %>
      </p>
      <p>
        <%= f.label :contents, "Directions" %>
      </p>
      <p>
        <%= f.text_area :contents, required: true %>
      </p>
      <p>
        <%= f.submit 'Save' %>
      </p>
    <% end %>
  </div>
  <%= link_to "New recipe", "#", onclick: "$('#new_recipe_forms').toggle()".html_safe %>
</div>
<h1>Recipes</h1>
<% if @recipes.present? %>
  <%= will_paginate @recipes %>
  <div id="recipes">
    <%= render partial: 'recipe', collection: @recipes %>
  </div>
  <%= will_paginate @recipes %>
<% else %>
  No recipes found.
<% end %>

app/views/recipes/show.html.erb
<%= render partial: 'recipe', object: @recipe %>